#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_midi = env_modules.Clone()

# MIDI / SoundFont playback: MidiStream (AudioStream) + TinySoundFont synth +
# TinyMidiLoader + importers. Standalone additive module (ADR 0008), standard
# module anatomy, auto-discovered by the build.
env_midi.add_source_files(env.modules_sources, "*.cpp")
